services:
  roundcubedb:
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    container_name: roundcubedb
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 9001:80
    env_file:
      - ./.env
volumes:
  mysql_data:
    driver: local
